version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan serve --host=127.0.0.1'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.32
    container_name: db
    restart: always
    tty: true
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: qwe2
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge